# New Q Value Formula


<img src="new-q-value-formula.png" />

In [15]:
# Import Libraries
import gym
import numpy as np

env = gym.make("MountainCar-v0")

In [16]:
# Define Constants
LEARNING_RATE = 0.1

DISCOUNT = 0.95
EPISODES = 25000
SHOW_EVERY = 3000

DISCRETE_OS_SIZE = [20, 20]

In [17]:
# Discrete Observation Space Window Size
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE
print(discrete_os_win_size)

[0.09  0.007]


In [18]:
# Exploration Settings (Epilipson)

epsilon = 1  # not a constant, going to be decayed
START_EPSILON_DECAYING = 1
END_EPSILON_DECAYING = EPISODES//2
epsilon_decay_value = epsilon/(END_EPSILON_DECAYING - START_EPSILON_DECAYING)

In [19]:
# Generate Q Table
q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))
print(q_table)

[[[-0.2341829  -0.86750922 -0.68485398]
  [-1.68630194 -0.46946581 -1.12396437]
  [-1.49955954 -1.6247043  -1.67467295]
  ...
  [-1.32668568 -1.40300399 -0.18923154]
  [-1.87897654 -0.78743303 -0.72826701]
  [-1.97359281 -1.53017818 -1.13620161]]

 [[-1.67721399 -1.52005015 -0.04530951]
  [-0.58017771 -1.21841716 -0.98542608]
  [-1.35860766 -1.89329942 -1.01172303]
  ...
  [-0.16762097 -1.81761799 -1.94075319]
  [-0.17421264 -1.46238871 -1.15233242]
  [-0.19929039 -0.37305163 -1.54856335]]

 [[-0.82775093 -1.59685759 -0.5650971 ]
  [-1.57378856 -1.4710741  -1.0808831 ]
  [-1.4778662  -1.90733164 -1.56265116]
  ...
  [-0.3099429  -0.46606701 -0.14325153]
  [-0.86766472 -0.35847534 -1.29605973]
  [-0.37107107 -0.61179773 -1.21878579]]

 ...

 [[-1.87030674 -0.36674264 -1.90681674]
  [-0.07114208 -0.24228295 -0.59908084]
  [-1.04897384 -0.62870183 -0.63278902]
  ...
  [-0.90376234 -1.62992007 -0.22285966]
  [-0.95269592 -1.65316842 -0.63779135]
  [-1.76529787 -0.31085041 -0.45290287]]

 [

In [20]:
# Method to get Discrete State
def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int))  # we use this tuple to look up the 3 Q values for the available actions in the q-table

# Exploration & Exploitation